name: 🐞 Bug report
description: Report an issue with unocss-preset-animations
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! If you have a usage question
        or are unsure if this is really a bug, make sure to:

        - Read the [documentation](https://unocss-preset-animations.aelita.me/) of using the package
        - Ask on [GitHub Discussion](https://github.com/xsjcTony/unocss-preset-animations/discussions)

  - type: input
    id: version
    attributes:
      label: unocss-preset-animations version
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to [StackBlitz](https://stackblitz.com/edit/vitejs-vite-lbg2ww?file=src%2FApp.tsx) or a github repo that can reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required).
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      placeholder: System, Browsers, Framework
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/xsjcTony/unocss-preset-animations/issues) that reports the same bug to avoid creating a duplicate
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/xsjcTony/unocss-preset-animations/discussions)
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug
          required: true
